-- MySQL Script generated by MySQL Workbench
-- Wed may 01 14:41:17 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyecto2_bases
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto2_bases
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto2_bases` DEFAULT CHARACTER SET utf8 ;
USE `proyecto2_bases` ;
 -- DROP DATABASE `proyecto2_bases`;
-- SHOW DATABASES LIKE 'proyecto2_bases';

-- -----------------------------------------------------
-- Table `proyecto2_bases`.`Historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2_bases`.`Historial` (
  `IdHistorial` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME NOT NULL,
  `Descripcion` VARCHAR(250) NOT NULL,
  `Tipo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`IdHistorial`)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `proyecto2_bases`.`Carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2_bases`.`Carrera` (
  `IdCarrera` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`IdCarrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2_bases`.`Plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2_bases`.`Plan` (
  `IdPlan` INT NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `AnioInicial` VARCHAR(4) NOT NULL,
  `CicloInicial` VARCHAR(50) NOT NULL,
  `AnioFinal` VARCHAR(4) NOT NULL,
  `CicloFinal` VARCHAR(50) NOT NULL,
  `NumCreditosCierre` INT NOT NULL,
  `IdCarrera` INT NOT NULL,
  PRIMARY KEY (`IdPlan`),
  INDEX `fk_Plan_Carrera1_idx` (`IdCarrera` ASC) VISIBLE,
  CONSTRAINT `fk_Plan_Carrera1`
    FOREIGN KEY (`IdCarrera`)
    REFERENCES `proyecto2_bases`.`Carrera` (`IdCarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2_bases`.`Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2_bases`.`Estudiante` (
  `Carnet` INT NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `Apellido` VARCHAR(50) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  `Correo` VARCHAR(50) NOT NULL,
  `Telefono` INT NOT NULL,
  `Direccion` VARCHAR(50) NOT NULL,
  `CUI` DOUBLE NOT NULL,
  `IdCarrera` INT NOT NULL,
  `IdPlan` INT NOT NULL,
  PRIMARY KEY (`Carnet`),
  INDEX `fk_Estudiante_Carrera1_idx` (`IdCarrera` ASC) VISIBLE,
  INDEX `fk_Estudiante_Plan1_idx` (`IdPlan` ASC) VISIBLE,
  CONSTRAINT `fk_Estudiante_Carrera1`
    FOREIGN KEY (`IdCarrera`)
    REFERENCES `proyecto2_bases`.`Carrera` (`IdCarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_Plan1`
    FOREIGN KEY (`IdPlan`)
    REFERENCES `proyecto2_bases`.`Plan` (`IdPlan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2_bases`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2_bases`.`Curso` (
  `CodigoCurso` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CodigoCurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2_bases`.`Pensum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2_bases`.`Pensum` (
  `CodigoCurso` INT NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `creditos_necesarios` INT NOT NULL,
  `creditos_otorga` INT NOT NULL,
  `obligatorio` INT NOT NULL,
  `IdPlan` INT NOT NULL,
  INDEX `fk_CursoPensum_Plan1_idx` (`IdPlan` ASC) VISIBLE,
  INDEX `fk_CursoPensum_Curso1_idx` (`CodigoCurso` ASC) VISIBLE,
  CONSTRAINT `fk_CursoPensum_Plan1`
    FOREIGN KEY (`IdPlan`)
    REFERENCES `proyecto2_bases`.`Plan` (`IdPlan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CursoPensum_Curso1`
    FOREIGN KEY (`CodigoCurso`)
    REFERENCES `proyecto2_bases`.`Curso` (`CodigoCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2_bases`.`Catedratico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2_bases`.`Catedratico` (
  `CodigoCat` INT NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `Apellido` VARCHAR(50) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  `Correo` VARCHAR(50) NOT NULL,
  `Telefono` INT NOT NULL,
  `Direccion` VARCHAR(50) NOT NULL,
  `CUI` BIGINT NOT NULL,
  `salario` INT NOT NULL,
  PRIMARY KEY (`CodigoCat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2_bases`.`Seccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2_bases`.`Seccion` (
  `IdSeccion` INT NOT NULL AUTO_INCREMENT,
  `CodigoCurso` INT NOT NULL,
  `Ciclo` VARCHAR(10) NOT NULL,
  `CodigoCat` INT NOT NULL,
  `Seccion` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`IdSeccion`),
  INDEX `fk_Seccion_Curso1_idx` (`CodigoCurso` ASC) VISIBLE,
  INDEX `fk_Seccion_Catedratico1_idx` (`CodigoCat` ASC) VISIBLE,
  CONSTRAINT `fk_Seccion_Curso1`
    FOREIGN KEY (`CodigoCurso`)
    REFERENCES `proyecto2_bases`.`Curso` (`CodigoCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Seccion_Catedratico1`
    FOREIGN KEY (`CodigoCat`)
    REFERENCES `proyecto2_bases`.`Catedratico` (`CodigoCat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2_bases`.`Asignacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2_bases`.`Asignacion` (
  `IdSeccion` INT NOT NULL,
  `Carnet` INT NOT NULL,
  INDEX `fk_Asignacion_Seccion1_idx` (`IdSeccion` ASC) VISIBLE,
  INDEX `fk_Asignacion_Estudiante1_idx` (`Carnet` ASC) VISIBLE,
  CONSTRAINT `fk_Asignacion_Seccion1`
    FOREIGN KEY (`IdSeccion`)
    REFERENCES `proyecto2_bases`.`Seccion` (`IdSeccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asignacion_Estudiante1`
    FOREIGN KEY (`Carnet`)
    REFERENCES `proyecto2_bases`.`Estudiante` (`Carnet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2_bases`.`Prerrequisito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2_bases`.`Prerrequisito` (
  `Curso` INT NOT NULL,
  `prerrequisito` INT NOT NULL,
  INDEX `fk_Prerrequisito_Curso1_idx` (`Curso` ASC) VISIBLE,
  INDEX `fk_Prerrequisito_Curso2_idx` (`prerrequisito` ASC) VISIBLE,
  CONSTRAINT `fk_Prerrequisito_Curso1`
    FOREIGN KEY (`Curso`)
    REFERENCES `proyecto2_bases`.`Curso` (`CodigoCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prerrequisito_Curso2`
    FOREIGN KEY (`prerrequisito`)
    REFERENCES `proyecto2_bases`.`Curso` (`CodigoCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2_bases`.`Periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2_bases`.`Periodo` (
  `IdPeriodo` INT NOT NULL,
  `HorarioInicio` TIME NOT NULL,
  `HorarioFinal` TIME NOT NULL,
  PRIMARY KEY (`IdPeriodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2_bases`.`Dia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2_bases`.`Dia` (
  `IdDia` INT NOT NULL,
  `Nombre` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`IdDia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2_bases`.`Salon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2_bases`.`Salon` (
  `IdSalon` INT NOT NULL,
  `NombreSalon` VARCHAR(10) NOT NULL,
  `Capacidad` INT NULL,
  `Edificio` VARCHAR(45) NULL,
  PRIMARY KEY (`IdSalon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2_bases`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2_bases`.`Horario` (
  `IdSeccion` INT NOT NULL,
  `IdPeriodo` INT NOT NULL,
  `IdDia` INT NOT NULL,
  `IdSalon` INT NOT NULL,
  INDEX `fk_Horario_Seccion1_idx` (`IdSeccion` ASC) VISIBLE,
  INDEX `fk_Horario_Periodo1_idx` (`IdPeriodo` ASC) VISIBLE,
  INDEX `fk_Horario_Dia1_idx` (`IdDia` ASC) VISIBLE,
  INDEX `fk_Horario_Salon1_idx` (`IdSalon` ASC) VISIBLE,
  CONSTRAINT `fk_Horario_Seccion1`
    FOREIGN KEY (`IdSeccion`)
    REFERENCES `proyecto2_bases`.`Seccion` (`IdSeccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Horario_Periodo1`
    FOREIGN KEY (`IdPeriodo`)
    REFERENCES `proyecto2_bases`.`Periodo` (`IdPeriodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Horario_Dia1`
    FOREIGN KEY (`IdDia`)
    REFERENCES `proyecto2_bases`.`Dia` (`IdDia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Horario_Salon1`
    FOREIGN KEY (`IdSalon`)
    REFERENCES `proyecto2_bases`.`Salon` (`IdSalon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2_bases`.`Notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2_bases`.`Notas` (
  `IdSeccion` INT NOT NULL,
  `Carnet` INT NOT NULL,
  `nota_zona` INT NOT NULL,
  `examen_final` INT NOT NULL,
  INDEX `fk_Notas_Seccion1_idx` (`IdSeccion` ASC) VISIBLE,
  INDEX `fk_Notas_Estudiante1_idx` (`Carnet` ASC) VISIBLE,
  CONSTRAINT `fk_Notas_Seccion1`
    FOREIGN KEY (`IdSeccion`)
    REFERENCES `proyecto2_bases`.`Seccion` (`IdSeccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notas_Estudiante1`
    FOREIGN KEY (`Carnet`)
    REFERENCES `proyecto2_bases`.`Estudiante` (`Carnet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2_bases`.`Desasignacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2_bases`.`Desasignacion` (
  `IdSeccion` INT NOT NULL,
  `Carnet` INT NOT NULL,
  INDEX `fk_Desasignacion_Seccion1_idx` (`IdSeccion` ASC) VISIBLE,
  INDEX `fk_Desasignacion_Estudiante1_idx` (`Carnet` ASC) VISIBLE,
  CONSTRAINT `fk_Desasignacion_Seccion1`
    FOREIGN KEY (`IdSeccion`)
    REFERENCES `proyecto2_bases`.`Seccion` (`IdSeccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Desasignacion_Estudiante1`
    FOREIGN KEY (`Carnet`)
    REFERENCES `proyecto2_bases`.`Estudiante` (`Carnet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
